site_name: Higher CS

theme:
    name: readthedocs

navigation_depth: 4

nav:
    - Home: index.md
    - SDD:
        - Software: sdd/H-CS-SDD.md
        - Procedures: sdd/H-CS-SDD-Procedures.md
        - Functions: sdd/H-CS-SDD-Functions.md
        - Type Hinting: sdd/H-CS-SDD-Types.md
        - Predefined funtions: sdd/H-CS-SDD-Predefined.md
        - Substrings: sdd/H-CS-SDD-Substrings.md
        - Parallel arrays: sdd/H-CS-SDD-Parallel.md
        - Records: sdd/H-CS-SDD-Records.md
        - Files: sdd/H-CS-SDD-Files.md
        - Reading data: sdd/H-CS-SDD-Reading.md
        - Writing data: sdd/H-CS-SDD-Writing.md
        - Standard algorithms: sdd/H-CS-SDD-Standard-Algorithms.md
    - DDD:
        - Databases: ddd/H-CS-DDD.md
        - Wildcards: ddd/H-CS-DDD-Wildcards.md
        - Aliases: ddd/H-CS-DDD-Alias.md
        - Computed values: ddd/H-CS-DDD-Computed.md
        - Aggregate functions: ddd/H-CS-DDD-Aggregate.md
        - Group By: ddd/H-CS-DDD-Grouping.md
        - Views: ddd/H-CS-DDD-View.md
        - Examples: ddd/H-CS-DDD-Examples.md

        